### ISSUE TITLE
Is it possible to modify response for preview?

### ISSUE THREAD

**Issue by yanghva** [httpyac/httpyac.github.io#11]
Great plugin! I am using in with VSCode. Sometimes I just need to extract part of the http response for preview. Is it possible? Tried following script, didn't work.
```
###
GET {{api}}

{{
  matched = response.body.match('regex');
  response.body = matched[0];
}}
```
`console.info` partially achieved what I wanted to do, but it had the leading 'INFO: ' label and it appended instead of truncating.

**Comment by AnWeber** [comment]
This is what the [responseLogging Hook](https://httpyac.github.io/plugins/plugin-api.html#responselogginghook) is for. But currently you can configure it only once for all requests in .httpyac.js. Your example seems more like you need this for a specific request. I will extend it.

**Comment by AnWeber** [comment]
I also noticed that your problem can also be solved using [event scrip@response](https://httpyac.github.io/guide/scripting.html#events). I'll still include an event @responseLogging, since that way you only edit the preview. @response also changes the result if it would be used in subsequent calls.

**Comment by AnWeber** [comment]
I have provided the changes with v4.7.0.  Now you should be able to change the output for the preview like this

```
###
GET {{api}}

{{@responseLogging
  matched = response.body.match('regex');
  response.body = matched[0];
  response.rawBody = Buffer.from(response.body); // used for preview
  delete response.prettyPrintBody;
}}
```

Please test. Thanks.

**Comment by yanghva** [comment]
> ~I also noticed that your problem can also be solved using [event script @response](https://httpyac.github.io/guide/scripting.html#events). I'll still include an event @responseLogging, since that way you only edit the preview. @response also changes the result if it would be used in subsequent calls.~ Found a bug. Access to response in @response event not working
> 
> Proposed change
> 
> ```
> ###
> GET {{api}}
> 
> {{@responseLogging
>   matched = response.body.match('regex');
>   response.body = matched[0];
>   response.rawBody = Buffer.from(response.body); // used for preview
>   delete response.prettyPrintBody;
> }}
> ```

Right, I did try the `response` event and noticed that it did not work.

However I found a better solution: `httpbook`. With that I was able to modify the output with a plain script just like what I posted in the beginning. `httpbook` worked exactly the way I liked: 1. being able to modify the response 2. showing response in the same editor. Great plugin!

I'll try the `responseLogging` later.

**Comment by yanghva** [comment]
> I have provided the changes with v4.7.0. Now you should be able to change the output for the preview like this
> 
> ```
> ###
> GET {{api}}
> 
> {{@responseLogging
>   matched = response.body.match('regex');
>   response.body = matched[0];
>   response.rawBody = Buffer.from(response.body); // used for preview
>   delete response.prettyPrintBody;
> }}
> ```
> 
> Please test. Thanks.

It worked, the trick is `response.rawBody = Buffer.from(response.body); // used for preview`. Maybe can document it somewhere?

Also I noticed it worked without hooking to `@responseLogging` explicitly, i.e.
```
###
GET {{api}}

{{
  matched = response.body.match('regex');
  response.body = matched[0];
  response.rawBody = Buffer.from(response.body); // used for preview
  delete response.prettyPrintBody;
}}
```
What's the default event the script hooks if it was not specified?

**Comment by AnWeber** [comment]
> With that I was able to modify the output with a plain script just like what I posted in the beginning. 

Surprised me just because I use here the [same interface as in vscode-httpyac](https://github.com/AnWeber/httpbook/blob/main/src/extension/notebook/httpNotebookKernel.ts#L177-L190), but take for the display the body. Please don't rely on this to stay that way, but rather use @responseLogging

> It worked, the trick is response.rawBody = Buffer.from(response.body); // used for preview. Maybe can document it somewhere?

I was thinking about converting httpResponse into a class and automatically synchronize the different body properties. I was going to think about it, but the as-is status is not good. This is the disadvantage that I intentionally make the interfaces so holey.

> What's the default event the script hooks if it was not specified?

There is actually no default event. I evaluate the http file like a javascript file, which is split into regions = functions and are processed from top to bottom. I convert the blocks into [callable functions](https://github.com/AnWeber/httpyac/blob/main/src/models/httpRegion.ts#L20). A script without an event is called exactly at this point in the sequence. Specifying events moves the script to the corrsponding hook. I needed this mainly for @streaming, because this is not solvable without events.
