### ISSUE TITLE
Cannot Export Token on Http Response

### ISSUE THREAD

**Issue by FrankRua** [httpyac/httpyac.github.io#12]
I have a global script that is defined at the top of my `.http` file for testing. The purpose of this script is to hit an endpoint to grab a bearer token to pass to as an HTTP header for testing. My code is as follows:

```
{{
// Script to grab our Bearer Token for testing.

const https = require('https');

var postData = new URLSearchParams({
    username: 'xxx',
    password: 'xxxx',
    grant_type: 'password',
    scope: 'xxx',
    client_id: 'xxx',
    client_secret: 'xxx'
});

var options = {
    hostname: 'xxx',
    port: 443,
    path: 'xxx',
    method: 'POST',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': postData.length
    }
};

var req = https.request(options, (res) => {
    let result = '';

    // Append our data to the result
    res.on('data', (dataChunk) => {
        result += dataChunk;
    });

    // Return compiled data
    res.on('end', () => {
        exports.authToken = JSON.parse(result).access_token;
    });
});

req.on('error', (e) => {
    console.error(e);
});

req.write(postData);
req.end();
}}
###

GET https://xxxx
Content-Type: application/json
Accept: application/json
Authorization: {{authToken}}
```

The first error I get is that `UrlSearchParams` is not defined, even though it is a standard package with Node. If I put this script into a Javascript file and run it via `node someJsFile.js` it executes without issue. Putting that aside, if I use the `querystring` package which is the legacy equivalent version I get an error saying that `authToken` is not defined. I have tried to move the script to the scope of only the one test as well and still get the same error.

I am using `httpyac@4.6.0`.

Any insight into this?

Thanks!

**Comment by AnWeber** [comment]
> The first error I get is that UrlSearchParams is not defined,

To make the variables easy to access. [the context of the script is switched](https://github.com/AnWeber/httpyac/blob/main/src/utils/moduleUtils.ts#L97-L109) (custom context instead of NodeJS default). I still try to add the most important methods or classes like Buffer to the global context, however, there may be deviations. To use UrlSearchParams I need an import of the Url package and therefore did not import it automatically. You can work around this behavior by importing your script using `require`, but then you don't have access to the variables and have to pass them to a function ([example](https://github.com/httpyac/httpyac.github.io/blob/main/examples/script/scriptRequire.http)).

> Putting that aside, if I use the querystring package which is the legacy equivalent version I get an error saying that authToken is not defined.

The cause is that my script cannot recognize that the code is async. The result is exported only after receiving the request, but by then the next http request has already been executed. The solution would be that you have to export a Promise, which is resolved on end([example](https://github.com/httpyac/httpyac.github.io/blob/main/examples/script/scriptPromise.http)).

```javascript
exports.wait = new Promise(resolve => {
...
res.on('end', () => {
        resolve(JSON.parse(result).access_token);
    });
...

]}
```

Is there a reason to use the `https` package?

I would solve your use case using [`@ref` and `@name`](https://github.com/httpyac/httpyac.github.io/blob/main/examples/metaData/ref.http).

```
# @name login
POST /login
Content-Type: application/x-www-form-urlencoded

username=john&password=123456&grant_type=password&scope=xxx&client_id=foo&client_secret=bar

GET /app
Authorization: Bearer {{login.access_token}}
```
and I notice that it is basically an OAuth2 Password Flow. I would use it like this, because then my extension manages the session and automatically makes a new session. If refresh_token is available it keeps the session open.

```
@oauth2_clientId=...
@oauth2_clientSecret=...
@oauth2_tokenEndpoint=...
@oauth2__username=...
@oauth2_password=...
@oauth2_scope=...

GET /app
Authorization: oauth2 password
```

**Comment by FrankRua** [comment]
@AnWeber Thanks for all the information, untimely I ended up utilizing your solution of using `@oauth2` that worked for me. I;ll close the issue now.

**Comment by AnWeber** [comment]
Thx:-)
