### ISSUE TITLE
Converting Header-Names to lower case?

### ISSUE THREAD

**Issue by carstenSpraener** [httpyac/httpyac.github.io#47]
It seems to me that httpyac (or its HTTP component)  converts HTTP-response-header names to lower case. This is different from the behavior of the IntelliJs HTTP component. 

This is a "workaround" but not very handy for larger number of http-Response-Headers:

```java-script
  client.global.set("callerId", response.headers.valueOf("XX-CallerId"));
  // httpyac hat hier sonst ein Problem
  if( client.global.get("callerId") == null ) {
    client.global.set("callerId", response.headers.valueOf("xx-callerid"));
  }
```

**Comment by AnWeber** [comment]
I'm not sure, but I suspect the conversion happens in [got](https://github.com/sindresorhus/got/blob/v11.8.3/source/core/index.ts#L1575). However, that shouldn't be a problem in itself, since the headers should be case insensitive: https://datatracker.ietf.org/doc/html/rfc7230#section-3.2
However, for your use case, I overlooked this and did not use my helper method. I correct it. Thanks for the hint.

**Comment by carstenSpraener** [comment]
Oh! That's quite fast responding. Thank you very much for the response. Totally agree, that headers shouldn't be case-sensitive. But unfortunately in IntelliJ thee are handled as case-sensitive. But... you fixed it... WOW!

By the way... Thank's for the library. Realy that is what I was looking for!
