### ISSUE TITLE
Error: No valid uri at Object.Wt.io.fileProvider.joinPath

### ISSUE THREAD

**Issue by jhonnycano** [httpyac/httpyac.github.io#51]
I am recently having this issue:

`POST https://httpbin.org/post
Content-Type: application/json

{
    "hello": "world"
}

`
Error: No valid uri at Object.Wt.io.fileProvider.joinPath (\.vscode\extensions\anweber.vscode-httpyac-5.5.4\dist\extension.js:305:7066) at Object.Wt.io.fileProvider.dirname (\.vscode\extensions\anweber.vscode-httpyac-5.5.4\dist\extension.js:305:6596) at aSe (\.vscode\extensions\anweber.vscode-httpyac-5.5.4\dist\extension.js:157:15784) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async O9.initHttpFile (\.vscode\extensions\anweber.vscode-httpyac-5.5.4\dist\extension.js:157:36535) at async O9.parse (\.vscode\extensions\anweber.vscode-httpyac-5.5.4\dist\extension.js:157:36124)
`

My httpyac.config.ts file:

`
// httpyac.config.js
module.exports = {
  // options...
  cookieJarEnabled: true,
  envDirName: '_env',
}
`

**Comment by AnWeber** [comment]
Your example works for me. I tested the following ways with `httpbook` and `vscode-httpyac`.
- Unsaved File, Untitled
- saved file in WSL 
- saved file in Windows

How can you trigger the error? Does it exist locally, in WSL or via SSH. Is the file opened in `httpbook` or using `vscode-httpyac` (Notebook Cells use scheme `vscode-notebook-cell` instead `file`). VSCode abstracts the [access to the file](https://code.visualstudio.com/api/extension-guides/virtual-workspaces) so that different protocols are supported. However, unfortunately not all of them support access to relative files. Only files with scheme `file` support joinPath. 
I have extended the logging for this error once and provided an update (v5.5.5)

**Comment by jhonnycano** [comment]
This is the new error:

Sorry I didn't mentioned before. The error occurs testing through the vscode extension of httpyac.

`
Error: No valid uri: vscode-userdata:/c%3A/Users/jcano/AppData/Roaming/Code/User/globalStorage/anweber.vscode-httpyac/_httpyac_/response
`

**Comment by AnWeber** [comment]
I have no idea yet how you manage to get the `response` opened with scheme `vscode-userdata`, however I can generate the error when I interpret the user settings of vscode as `http` file.
- open `File - Preferences - Settings` and open Settings in Editor
- change Language Mode from `JSONC` to `http`
- scheme `vscode-userdata` is used to open file.

But since the Scheme behaves basically like scheme `file` I simply adjusted the access in my abstraction layer.

**Comment by jhonnycano** [comment]
It might have to be related to the fact that I use Response View Content = "full". The error also occurs in "exchange" mode, but does not occur in "body" mode.

**Comment by AnWeber** [comment]
I already suspected that, otherwise the `response` file would not be parsed using `initHttpFile`. Just as you probably set the `httpyac.responseViewMode=reuse` setting, otherwise [the filename would not be generated that way](https://github.com/AnWeber/vscode-httpyac/blob/main/src/view/editorResponseHandler.ts#L34). But I still don't understand why writing the file into the [`context.globalStorageUri`](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext) creates a Uri with scheme `vscode-userdata`. On my system it is scheme `file`. For this reason my fix is more or less a test right now, because I don`t understand the reason yet.

**Comment by jhonnycano** [comment]
The fixed worked fine, thanks a lot!

**Comment by AnWeber** [comment]
thx for the feedback
