### ISSUE TITLE
Future Feature - "borrow" from hurl - xpath, jsonpath

### ISSUE THREAD

**Issue by chrismalek** [httpyac/httpyac.github.io#62]
Tag: Idea, Future Feature, Discussion, Low priority

I don't really want to file this as an issue but GitHub discussions are not enabled on this project. 

I recently discovered [hurl](https://hurl.dev) which has some cool qualities. There are many things that httpyac does better. Namely the environment support is way better in httpyac. As all software pros and cons. I realize that. They are designed with slightly different use cases but there is a bunch of overlapping features.

One thing that I think hurl has that I love is the built in support in the grammar for both xpath and json path. That is documented in in the [hurl asserting response page](https://hurl.dev/docs/asserting-response.html)

This seems to be much more simple syntax than the httpyac Javascript. 

I was playing around with hurl in my off my projects and the asserts were super simple using jsonpath. It looks something like this:

```text
HTTP/1.1 200
[Asserts]
jsonpath "$.responseCode" == 200
jsonpath "$.matchCount" == 1
jsonpath "$.matches[0].emplid" == "ADCRM1004"
jsonpath "$.matches[0].searchRuleCode" == "NID"
jsonpath "$.matches[0].SRVC_IND_DATA.fields[0].SRVC_IND_CD" == "DEP"
jsonpath "$.matches[0].SRVC_IND_DATA.fields[1].SRVC_IND_CD" == "DNP"

```

I realize that you can do javascripting in httpyac but to be honest I am too lazy to figure out the syntax and debug it.  This hurl model seems really simple.

Just a thought if a contributor has the knowledge to implement this it would be "cool".  Again, this is just an idea/feature request.  

Take is under consideration. 

--- 

HttpYac Accolades

I have said it before but I will say it again.  I love httpyac. I use it every day all day doing API integration work for my own dev and clients.  Love it. Great work. Thank you so much.

**Comment by AnWeber** [comment]
Thanks for the tip about this app. The asserts are really easy to write. Especially since XPath is also directly included. I'll take a look at it and try to improve the assert feature in my extensions. Say for basic asserts a simple syntax. For extended asserts using javascript. 
I already included a [test helper](https://github.com/AnWeber/httpyac/blob/main/src/utils/testUtils.ts#L40-L86). But it is probably too hidden and not documented enough.

```
GET /json

{{
  test.status(200);
}}
```

> I have said it before but I will say it again. I love httpyac.

All good and thanks anyway:-) I am the first to know that any line of code that is not mine is good code. Less to wait and worry about. The whole thing is a fun project of mine and if there is a good alternative project, I am happy to support there as well. Currently I don't have the time to push httpyac, but there would be some ideas for further improvement.

**Comment by AnWeber** [comment]
I have now tried a simple syntax. It would be nice if you try this once. Thank you.

```
GET https://httpbin.org/anything

?? status == 200

```

https://httpyac.github.io/guide/assert.html

**Comment by chrismalek** [comment]
Amazing..I will give it a whirl. I am doing of a bunch of API development and testing in the next few days so I will get this hooked up.  HTTPYAC forever !   :-)
