### ISSUE TITLE
response.headers.headers to access the headers.

### ISSUE THREAD

**Issue by drago1520** [httpyac/httpyac.github.io#81]
# Problem: I need to access response.headers.headers instead of response.headers as per documentation
## Setup
1. ExpressJs with custom auth middleware that only sents the cookies
2. Windows with git bash terminal and vs code
### Code to replicate
1. Make sure the server is up and running
2. Remove the '' quotes from my code at the beginning and end 

> '### Create a subscription (good weather test)
> POST http://localhost:3000/api/subscriptions
> Content-Type: application/json
> Origin: http://localhost:3000
> 
> {
>   "email": "subscriber@example.com"
> }
> 
> > {%
>     
>     client.test("Create subscription - good weather test", function() {
>         // Log all keys in the response headers
>         const headers = response.headers.headers;
>         Object.keys(headers).forEach(key => {
>             console.log(key);
>         });
>         client.assert(response.status === 201, "Response status should be 201");
>         client.assert(response.body.message === "Subscription created successfully", "Response body should contain the correct success message");
>         
>     });
> %}'

**Comment by AnWeber** [comment]
I don't understand the ticket right now. Do you want to use it like this and it doesn't work, or do you currently have to call the API like this? The latter would be wrong.

**Comment by drago1520** [comment]
I have to call response.header.header to actually get the headers. I am using expressjs and i am not adding any headers manually.

**Comment by AnWeber** [comment]
Now I'm back in context. You are using the Intellij HTTP Client API here. Access in this API is not via property but via `valueOf`. see https://www.jetbrains.com/help/idea/http-response-reference.html#headers-reference.
[The fact that the concept with response.headers.headers works here is simple, because Typescript private is not really private.](https://github.com/AnWeber/httpyac/blob/main/src/plugins/intellij/api/intellijHttpResponse.ts#L27) 
Please use the correct Intellij syntax or change the brackets to `{{`, then the direct access via response.headers will also work.
